In [1]:
import pandas as pd

# The notebook is inside /notebook, so ../data/ means "go up one folder, then into data"
DATA = "../data/"

# encoding="latin-1" is needed because these files are not UTF-8
debt_raw    = pd.read_csv(DATA + "IDS_ALLCountries_Data.csv", encoding="latin-1")
country_raw = pd.read_csv(DATA + "IDS_CountryMetaData.csv", encoding="latin-1")
series_raw  = pd.read_csv(DATA + "IDS_SeriesMetaData.csv", encoding="latin-1")

print("Files loaded")

Files loaded

In [2]:
print("Main debt data:  ", debt_raw.shape)
print("Country metadata:", country_raw.shape)
print("Series metadata: ", series_raw.shape)

Main debt data:   (62983, 39)
Country metadata: (134, 30)
Series metadata:  (574, 12)

In [3]:
debt_raw.head()

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,2000,2001,2002,2003,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032
0,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.DPPG,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.OFFT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.PRVT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.DPPG,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.OFFT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
country_raw.head()

,Code,Long Name,Income Group,Region,Lending category,Other groups,Currency Unit,Latest population census,Latest household survey,Special Notes,...,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,2-alpha code,WB-2 code,Table Name,Short Name
0,AFG,Islamic State of Afghanistan,Low income,Middle East & North Africa,IDA,HIPC,Afghan afghani,1979,Multiple Indicator Cluster Survey 2022-2023,The reporting period for national accounts dat...,...,"Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,2000.0,AF,AF,Afghanistan,Afghanistan
1,ALB,Republic of Albania,Upper middle income,Europe & Central Asia,IBRD,NaN,Albanian lek,2023,Demographic and Health Survey 2017 - 2018,NaN,...,Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2018.0,2006.0,AL,AL,Albania,Albania
2,DZA,People's Democratic Republic of Algeria,Upper middle income,Middle East & North Africa,IBRD,NaN,Algerian dinar,2022,Multiple Indicator Cluster Survey 2018-2019,NaN,...,"Integrated household survey (IHS), 2011",NaN,NaN,2010.0,2017.0,2012.0,DZ,DZ,Algeria,Algeria
3,AGO,People's Republic of Angola,Lower middle income,Sub-Saharan Africa,IBRD,NaN,Angolan kwanza,2014,Demographic and Health Survey 2015/16,The World Bank systematically assesses the app...,...,"Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2018.0,2005.0,AO,AO,Angola,Angola
4,ARG,Argentine Republic,Upper middle income,Latin America & Caribbean,IBRD,NaN,Argentine peso,2022,Multiple Indicator Cluster Survey 2019-2020,The World Bank systematically assesses the app...,...,"Integrated household survey (IHS), 2016",Yes,2008,2002.0,2018.0,2011.0,AR,AR,Argentina,Argentina

In [5]:
series_raw.head()

,Code,License Type,Indicator Name,Short definition,Long definition,Source,Topic,Dataset,Periodicity,Aggregation method,Limitations and exceptions,General comments
0,DT.GPA.DPPG,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
1,DT.GPA.OFFT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
2,DT.GPA.PRVT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
3,DT.GRE.DPPG,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
4,DT.GRE.OFFT,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN

In [6]:
print(debt_raw.columns.tolist())
print(country_raw.columns.tolist())
print(series_raw.columns.tolist())

['Country Name', 'Country Code', 'Counterpart-Area Name', 'Counterpart-Area Code', 'Series Name', 'Series Code', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029', '2030', '2031', '2032']
['Code', 'Long Name', 'Income Group', 'Region', 'Lending category', 'Other groups', 'Currency Unit', 'Latest population census', 'Latest household survey', 'Special Notes', 'National accounts base year', 'National accounts reference year', 'System of National Accounts', 'SNA price valuation', 'PPP survey years', 'Balance of Payments Manual in use', 'External debt Reporting status', 'System of trade', 'Government Accounting concept', 'IMF data dissemination standard', 'Source of most recent Income and expenditure data', 'Vital registration complete', 'Latest agricultural census', 'Latest industrial data', 'Latest trade data', 'Latest water withdrawal data', '2-alpha code', 'WB-2 code', 'Table Name', 'Short Name']
['Code', 'License Type', 'Indicator Name', 'Short definition', 'Long definition', 'Source', 'Topic', 'Dataset', 'Periodicity', 'Aggregation method', 'Limitations and exceptions', 'General comments']

In [7]:
debt_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 62983 entries, 0 to 62982
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country Name           62980 non-null  str
 1   Country Code           62978 non-null  str
 2   Counterpart-Area Name  62978 non-null  str
 3   Counterpart-Area Code  62978 non-null  str
 4   Series Name            62978 non-null  str
 5   Series Code            62978 non-null  str
 6   2000                   49490 non-null  float64
 7   2001                   49434 non-null  float64
 8   2002                   49262 non-null  float64
 9   2003                   49001 non-null  float64
 10  2004                   49195 non-null  float64
 11  2005                   49137 non-null  float64
 12  2006                   49394 non-null  float64
 13  2007                   49645 non-null  float64
 14  2008                   49497 non-null  float64
 15  2009                   49768 non-null  float64
 16  2010                   49761 non-null  float64
 17  2011                   49080 non-null  float64
 18  2012                   49008 non-null  float64
 19  2013                   49379 non-null  float64
 20  2014                   50504 non-null  float64
 21  2015                   50431 non-null  float64
 22  2016                   50192 non-null  float64
 23  2017                   50333 non-null  float64
 24  2018                   50296 non-null  float64
 25  2019                   50493 non-null  float64
 26  2020                   50956 non-null  float64
 27  2021                   50727 non-null  float64
 28  2022                   50721 non-null  float64
 29  2023                   50641 non-null  float64
 30  2024                   50590 non-null  float64
 31  2025                   12855 non-null  float64
 32  2026                   12760 non-null  float64
 33  2027                   12622 non-null  float64
 34  2028                   12432 non-null  float64
 35  2029                   12138 non-null  float64
 36  2030                   11967 non-null  float64
 37  2031                   11771 non-null  float64
 38  2032                   11566 non-null  float64
dtypes: float64(33), str(6)
memory usage: 24.3 MB

In [8]:
country_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 30 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Code                                               134 non-null    str
 1   Long Name                                          134 non-null    str
 2   Income Group                                       119 non-null    str
 3   Region                                             120 non-null    str
 4   Lending category                                   120 non-null    str
 5   Other groups                                       40 non-null     str
 6   Currency Unit                                      120 non-null    str
 7   Latest population census                           118 non-null    str
 8   Latest household survey                            120 non-null    str
 9   Special Notes                                      60 non-null     str
 10  National accounts base year                        120 non-null    str
 11  National accounts reference year                   39 non-null     float64
 12  System of National Accounts                        120 non-null    str
 13  SNA price valuation                                120 non-null    str
 14  PPP survey years                                   116 non-null    str
 15  Balance of Payments Manual in use                  118 non-null    str
 16  External debt Reporting status                     120 non-null    str
 17  System of trade                                    100 non-null    str
 18  Government Accounting concept                      97 non-null     str
 19  IMF data dissemination standard                    117 non-null    str
 20  Source of most recent Income and expenditure data  116 non-null    str
 21  Vital registration complete                        36 non-null     str
 22  Latest agricultural census                         71 non-null     str
 23  Latest industrial data                             85 non-null     float64
 24  Latest trade data                                  113 non-null    float64
 25  Latest water withdrawal data                       112 non-null    float64
 26  2-alpha code                                       134 non-null    str
 27  WB-2 code                                          134 non-null    str
 28  Table Name                                         134 non-null    str
 29  Short Name                                         134 non-null    str
dtypes: float64(4), str(26)
memory usage: 113.3 KB

In [9]:
series_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 574 entries, 0 to 573
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Code                        574 non-null    str
 1   License Type                2 non-null      str
 2   Indicator Name              574 non-null    str
 3   Short definition            572 non-null    str
 4   Long definition             574 non-null    str
 5   Source                      574 non-null    str
 6   Topic                       574 non-null    str
 7   Dataset                     573 non-null    str
 8   Periodicity                 574 non-null    str
 9   Aggregation method          574 non-null    str
 10  Limitations and exceptions  1 non-null      str
 11  General comments            8 non-null      str
dtypes: str(12)
memory usage: 743.8 KB

In [10]:
print(debt_raw.isna().sum().head(8))
print("Duplicate rows:", debt_raw.duplicated().sum())

Country Name                 3
Country Code                 5
Counterpart-Area Name        5
Counterpart-Area Code        5
Series Name                  5
Series Code                  5
2000                     13493
2001                     13549
dtype: int64
Duplicate rows: 2

In [11]:
print(country_raw.isna().sum().head(8))
print("Duplicate rows:", country_raw.duplicated().sum())

Code                         0
Long Name                    0
Income Group                15
Region                      14
Lending category            14
Other groups                94
Currency Unit               14
Latest population census    16
dtype: int64
Duplicate rows: 0

In [12]:
print(series_raw.isna().sum().head(12))

print("Duplicate rows:", series_raw.duplicated().sum())

Code                            0
License Type                  572
Indicator Name                  0
Short definition                2
Long definition                 0
Source                          0
Topic                           0
Dataset                         1
Periodicity                     0
Aggregation method              0
Limitations and exceptions    573
General comments              566
dtype: int64
Duplicate rows: 0

In [13]:
debt_raw.tail(6).iloc[:, :4]

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code
62977,Zimbabwe,ZWE,World,WLD
62978,NaN,NaN,NaN,NaN
62979,NaN,NaN,NaN,NaN
62980,NaN,NaN,NaN,NaN
62981,Data from database: International Debt Statistics,NaN,NaN,NaN
62982,Last Updated: 12/03/2025,NaN,NaN,NaN

In [14]:
country_raw[["Code", "Long Name", "Income Group", "Region"]].head()

,Code,Long Name,Income Group,Region
0,AFG,Islamic State of Afghanistan,Low income,Middle East & North Africa
1,ALB,Republic of Albania,Upper middle income,Europe & Central Asia
2,DZA,People's Democratic Republic of Algeria,Upper middle income,Middle East & North Africa
3,AGO,People's Republic of Angola,Lower middle income,Sub-Saharan Africa
4,ARG,Argentine Republic,Upper middle income,Latin America & Caribbean

In [15]:
print("Countries/groups in debt data:", debt_raw["Country Code"].nunique())
print("Indicators in debt data:      ", debt_raw["Series Code"].nunique())

Countries/groups in debt data: 134
Indicators in debt data:       576